#
# Build steps.
#
steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - airport-code-lookup
  - --region=europe-west1
  - --source=.
  - --trigger-http
  - --runtime=RUNTIME
timeout: 300s