#
# Build steps.
#
steps:
- name: node
  entrypoint: npm
  args: ['install']
- name: node
  entrypoint: npm
  args: ['test']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - airport-code-lookup-2
  - --region=europe-west1
  - --source=.
  - --trigger-http
  - --runtime=nodejs16
timeout: 300s